import = [
  "~/.config/alacritty/synthwave84_theme.toml"
]

[window]
decorations = "None" 

[window.padding]
x = 5
y = 10

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"
