[colors.primary]
background = "#262335"
foreground = "#ffffff"

[colors.cursor]
text = "#03edf9"
cursor = "#ffffff"

[colors.normal]
black = "0x26233a"
red = "#fe4450"
green = "#72f1b8"
yellow = "#f3e70f"
blue = "0x9ccfd8"
magenta = "#ff7edb"
cyan = "#03edf9"
white = "0xe0def4"

[colors.bright]
black = "0x6e6a86"
red = "#fe4450"
green = "#72f1b8"
yellow = "#fede5d"
blue = "#03edf9"
magenta = "#ff7edb"
cyan = "#03edf9"
white = "0xe0def4"

